version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=us-east-1
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/brain-tasks
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Build started on `date`

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t brain-tasks .
      - docker tag brain-tasks:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - echo Applying Kubernetes manifests...
      - aws eks update-kubeconfig --region us-east-1 --name brain-tasks-eks
      - kubectl apply -f k8s/

artifacts:
  files:
    - '**/*'

